Repository DIPSAS/DIPS.Xamarin.UI, pull requests merged in 2019-12, with the labels that each got.

#61 Set `HasBorder` to obsolete and removed code to turn toggle it in plat…
  src/DIPS.Xamarin.UI.Android/Renderers/DatePicker/DatePickerImplementation.cs
  src/DIPS.Xamarin.UI.iOS/Renderers/DatePicker/DatePickerImplementation.cs
  src/DIPS.Xamarin.UI/Controls/DatePicker/DatePicker.cs
  src/Samples/DIPS.Xamarin.UI.Samples/Controls/DatePicker/DatePickerPage.xaml
Labels: breaking-change, ui

#69 Renamed `RaiseAfter` to `RaiseWhenSet`
  src/DIPS.Xamarin.UI.sln
  src/DIPS.Xamarin.UI/Controls/DatePicker/DatePicker.cs
  src/DIPS.Xamarin.UI/Extensions/PropertyChangedExtensions.cs
  src/IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro.iOS/DIPS.Xamarin.Forms.IssuesRepro.iOS.csproj
  src/Samples/DIPS.Xamarin.UI.Samples/Extensions/PropertyChangedViewModel.cs
Labels: api

#67 Changed layout of radioButtonGroup
  src/DIPS.Xamarin.UI/Controls/RadioButtonGroup/RadioButtonGroup.xaml
  src/DIPS.Xamarin.UI/Controls/RadioButtonGroup/RadioButtonGroup.xaml.cs
  src/IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro.Android/DIPS.Xamarin.Forms.IssuesRepro.Android.csproj
  src/IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro/DIPS.Xamarin.Forms.IssuesRepro.iOS/DIPS.Xamarin.Forms.IssuesRepro.iOS.csproj
  src/Samples/DIPS.Xamarin.UI.Samples/Controls/RadioButtonGroup/RadioButtonGroupPage.xaml
Labels: ui

#77 Added DateConverter, TimeConverter and DateAndTimeConverter
  src/DIPS.Xamarin.UI.sln
  src/DIPS.Xamarin.UI/AssemblyInfo.cs
  src/DIPS.Xamarin.UI/Converters/ValueConverters/DateAndTimeConverter.cs
  src/DIPS.Xamarin.UI/Converters/ValueConverters/DateConverter.cs
  src/DIPS.Xamarin.UI/Converters/ValueConverters/TimeConverter.cs
  src/DIPS.Xamarin.UI/DIPS.Xamarin.UI.csproj
  src/DIPS.Xamarin.UI/Extensions/CultureInfoExtensions.cs
  src/DIPS.Xamarin.UI/Extensions/DateTimeExtensions.cs
  src/DIPS.Xamarin.UI/InternalUtils/Clock.cs
  src/DIPS.Xamarin.UI/Resources/LocalizedStrings/InternalLocalizedStrings.Designer.cs
  src/DIPS.Xamarin.UI/Resources/LocalizedStrings/InternalLocalizedStrings.no.resx
  src/DIPS.Xamarin.UI/Resources/LocalizedStrings/InternalLocalizedStrings.resx
  src/Samples/DIPS.Xamarin.UI.InternalShared/DIPS.Xamarin.UI.InternalShared.csproj
  src/Samples/DIPS.Xamarin.UI.InternalShared/IMobileSettings.cs
  src/Samples/DIPS.Xamarin.UI.InternalShared/MobileSettings.cs
  src/Samples/DIPS.Xamarin.UI.Samples.Android/DIPS.Xamarin.UI.Samples.Android.csproj
  src/Samples/DIPS.Xamarin.UI.Samples.Android/MainActivity.cs
  src/Samples/DIPS.Xamarin.UI.Samples.Android/MobileSettings/AndroidSettings.cs
  src/Samples/DIPS.Xamarin.UI.Samples.iOS/AppDelegate.cs
  src/Samples/DIPS.Xamarin.UI.Samples.iOS/DIPS.Xamarin.UI.Samples.iOS.csproj
  src/Samples/DIPS.Xamarin.UI.Samples.iOS/MobileSettings/iPhoneSettings.cs
  src/Samples/DIPS.Xamarin.UI.Samples/Converters/ConvertersPage.xaml
  src/Samples/DIPS.Xamarin.UI.Samples/Converters/ConvertersViewModel.cs
  src/Samples/DIPS.Xamarin.UI.Samples/Converters/ValueConverters/DateAndTimeConverterPage.xaml
  src/Samples/DIPS.Xamarin.UI.Samples/Converters/ValueConverters/DateAndTimeConverterPage.xaml.cs
  src/Samples/DIPS.Xamarin.UI.Samples/Converters/ValueConverters/DateConverterPage.xaml
  src/Samples/DIPS.Xamarin.UI.Samples/Converters/ValueConverters/DateConverterPage.xaml.cs
  src/Samples/DIPS.Xamarin.UI.Samples/Converters/ValueConverters/TimeConverterPage.xaml
  src/Samples/DIPS.Xamarin.UI.Samples/Converters/ValueConverters/TimeConverterPage.xaml.cs
  src/Samples/DIPS.Xamarin.UI.Samples/DIPS.Xamarin.UI.Samples.csproj
  src/Tests/DIPS.Xamarin.UI.Tests/Converters/ValueConverters/DateAndTimeConverterTests.cs
  src/Tests/DIPS.Xamarin.UI.Tests/Converters/ValueConverters/DateConverterTests.cs
  src/Tests/DIPS.Xamarin.UI.Tests/Converters/ValueConverters/TimeConverterTests.cs
  src/Tests/DIPS.Xamarin.UI.Tests/DIPS.Xamarin.UI.Tests.csproj
  src/Tests/DIPS.Xamarin.UI.Tests/TestHelpers/ValueConverterExtensions.cs
Labels: api, enhancement

#80 Added comma to norwegian short format
  src/DIPS.Xamarin.UI/Converters/ValueConverters/DateAndTimeConverter.cs
  src/Tests/DIPS.Xamarin.UI.Tests/Converters/ValueConverters/DateAndTimeConverterTests.cs
Labels: bug, ui

#81 Added IsEmptyToObjectConverter
  src/DIPS.Xamarin.UI/Converters/ValueConverters/IsEmptyToObjectConverter.cs
  src/Samples/DIPS.Xamarin.UI.Samples/Converters/ConvertersPage.xaml
  src/Samples/DIPS.Xamarin.UI.Samples/Converters/ConvertersViewModel.cs
  src/Samples/DIPS.Xamarin.UI.Samples/Converters/ValueConverters/IsEmptyToObjectConverterPage.xaml
  src/Samples/DIPS.Xamarin.UI.Samples/Converters/ValueConverters/IsEmptyToObjectConverterPage.xaml.cs
  src/Samples/DIPS.Xamarin.UI.Samples/DIPS.Xamarin.UI.Samples.csproj
  src/Tests/DIPS.Xamarin.UI.Tests/Converters/ValueConverters/IsEmptyToObjectConverterTests.cs
Labels: enhancement, ui
